### ISSUE TITLE
Routes are not being prepended

### ISSUE THREAD

**Issue by psharpNumerex** [modeset/teaspoon#191]
Upgraded to 8 and it seems that the routes are not being prepended.

I tracked it down to engine.rb:43

return if Teaspoon::Engine.routes.recognize_path('/') rescue nil

outputting the results of Teaspoon::Engine.routes.recognize_path('/') gives me
{:controller=>"teaspoon/suite", :action=>"index"}

I'm using Rails 3.2.17

**Comment by hlascelles** [comment]
We did a cleanup of some engines and saw this error arise (with 0.8.0). It turns out that our [Combustion](https://github.com/pat/combustion) folders needed a NOOP *routes.rb* file to trigger the correct append to take place.

That is to say, adding the following file to _spec/internal/config/routes.rb_ solved the problem:

````
Rails.application.routes.draw do
   # Do nothing, except trigger automatic teaspoon engine mount
end
````

**Comment by jejacks0n** [comment]
That's probably true because we use that "event" as the time to hook in.

---
Jeremy Jackson

**Comment by mikeantonelli** [comment]
@hlascelles do you have an example of using teaspoon and combustion to test a Rails engine?

**Comment by hlascelles** [comment]
Apologies @mikeantonelli I've just seen this! No we don't I'm afraid. Just rather a large and convoluted engine. If / when it is broken down I will post one...
