### ISSUE TITLE
Loading of fixtures vs application code vs "document ready" ;)

### ISSUE THREAD

**Issue by rstudner** [modeset/teaspoon#307]
Really simple.

I have some .js files that have the canonical $(document).ready(function() { // do some stuff }

I have a fixture file with a bit O static HTML in it.

So, the problem is insanely simple..  the order of loading/running is this:
my .js file & its document onready 100% run
.
.
.
.
.
the fixture gets loaded.

Thus, if my document.ready expects *anything to be in the DOM from the fixture file at all* -- it isn't there.

App works 100% fine outside of tests :)

What the heck :)?

**Comment by jejacks0n** [comment]
Consider preloading your fixtures? That's in the docs, and I think works how you want.

---
Jeremy Jackson

**Comment by jejacks0n** [comment]
Consider using the `jQuery(function() {})` style instead of the document ready style as well. Reads nice imo.

---
Jeremy Jackson

**Comment by rstudner** [comment]
I saw the preload docs and tried it but it had absolutely no effect of any kind.  I'm running teaspoon 0.7.9 btw.

I have a fixture file with <div id="foo"></div> in it

my jquery(function() { 
         does something with that foo
      });

my test preloads the fixture.. then actually loads the fixture in a beforeEach

Then in a describe/it just does expect($("div#foo").length).toEqual(1); 

And that always fails, since it is "zero" (since the div isn't in "teaspoons test executor DOM at the time of the expect being executed).

**Comment by rstudner** [comment]
You know -- I think this might be somehow unrelated to teaspoon (versus some weird asset pipeline issue)
When I look at the network tab, while doing localhost:3000/teaspoon I see this:
<all my js loads>
<fixture loads>

my test has like:

//= require support/jasmine-jquery
//= require folder/myjs

<now here is the test>
preload fixture
describe
  beforeEach
    loadTheFixture
  describe
     it
       test for something


So the issue, is that my javascript literally is just loading/running before the fixture ever gets into the DOM (at all).

Just seems like nothing I can do "in the spec file and with teaspoon" can possibly fix this.

hrm.

**Comment by rstudner** [comment]
And -- running things from the command line always yields totally different results than running localhost:3000/teaspoon.

I can make things pass in one environment -- then they fail in the other -- and vice versa.

**Comment by rstudner** [comment]
<pre>
$(document).ready(function () {
  var checkState = function() {
      if ($("#incident-header").length == 0) {
        console.debug($('div'));
        setTimeout(checkState, 500);
      } else {
        //actual code would go here
      }
    };
    setTimeout(checkState, 500);
});
</pre>

As an example.  The above works just fine if I just run my app normally.

if I run a teaspoon test with the above, the $("#incident-header") will fail, 100% of the time. 

The fixture I both preloaded, and loaded, has a div with that ID in it.

**Comment by rstudner** [comment]
Is the above normal -- that when I do localhost:3000/teaspoon and view my network tab, that *all* my javascript is loaded BEFORE the fixture  (and thus, no matter what, anything in $(document).ready *will be run no matter what before the fixture is available* 

Or is that not normal?  (trying to see if there is something about the rails app i'm working on that is doing something weird with asset loading order in general)

**Comment by jejacks0n** [comment]
Not sure, loading is entirely up to you. I recommend writing your tests with proper dependency requirements. For instance, your spec helper should only load library code (eg. jQuery/moment/underscore etc.) and then your spec files should require what they use. That way your spec_helper is loaded, then your spec files (or spec file if running a focused spec), then any fixtures, then any implementation files. If you're loading everything from application.js or something similar you may have complications. I prefer the scalpel and load only what's need for a spec to pass, but understand a lot of people use a hammer. I don't have a solution for the hammer approach, which is sort of why I dislike it and don't use it.

**Comment by jejacks0n** [comment]
It looks like you want to load your fixture into the dom before the beforeEach is called, fwiw.. how do you accomplish that? You may be able to accomplish that by injecting it when the file is executed, and not before the test is run -- like, before your test even runs you're already doing a bunch of setup in your application, no?

So that means your current situation is, javascripts are parsed, application is initialized, test run begins. After which point, your beforeEach is called.

Looks like you'll need to inject your dom manipulations before the application is initialized. You can experiment with manipulating the dom at the time the spec file is being executed, and not when the specs are being run -- if that makes sense. Try adding something to the dom at the base of the file and not within the beforeEach.

Another approach, and one that I'd recommend, is to not initialize your application until you need it. For the most part teaspoon is a unit test framework, but you can use it for more integration level tests if you want -- you just need to know the issues that can arise by doing so.
