### ISSUE TITLE
Coverage Number not changing

### ISSUE THREAD

**Issue by Codebryo** [modeset/teaspoon#412]
Hi, I have a question about the coverage numbers. 
Initially I have some numbers. I added more tests, those specs run but the coverage number is not rising or shrinking. 
Can I somehow see what files are used for counting the coverage? The docs are vague on this.

**Comment by jejacks0n** [comment]
Yup, read up on istanbul, and teaspoon configuration (specifically coverage). You can generate html output that you can browse to see what is covered and what isn't covered. If you're not improving on what lines are being executed, it doesn't matter how many specs you add. I use the html output almost exclusively during development, because that's what actually matters if you want to improve it.
