### ISSUE TITLE
Fail test on parse error

### ISSUE THREAD

**Issue by pratik60** [modeset/teaspoon#425]
Hi Guys

Really wondering why tests are not considered to fail when there is a parse error? Because of a parse error, it didn't run all the tests, and definitely should have ultimately result in a fail.

Any reason why the current behaviour is like that?

Starting the Teaspoon server...
...
Teaspoon running default suite at http://127.0.0.1:61748/teaspoon/default
SyntaxError: Parse error

......*..........................................................................................................................................................................................................................................................*...................

Finished in 4.42400 seconds
277 examples, 0 failures, 2 pending

**Comment by mikepack** [comment]
How are you producing the parse error? The success or failure of a build is determined by whether you have any failing specs. In your example, nothing failed, so that's why it's a successful build.

**Comment by jejacks0n** [comment]
We get these issues from time to time. It's because the order of how JavaScript is loaded and parsed. If there's a parse error, it's long before any JavaScript has the opportunity to do anything, and regardless, there's not a JavaScript exception raised or anything.

We could punt on execution of the specs (maybe), but a parse error is not indicative of if your javascript execute in the real world or not. So in stead you get the message.

**Comment by pratik60** [comment]
@mikepack @jejacks0n - We have 302 tests that are there...Because of a parse error, I'm assuming in the tests itself, some of them just didn't run! 

Surely that is something that should be caught by teaspoon?

**Comment by jejacks0n** [comment]
I'm willing to entertain it. Feel free to submit a pr.

**Comment by mikepack** [comment]
I still don't understand how this error is being produced. Syntax errors in the specs or implementation bubble up as errors in the console output. @pratik60 can you explain how to produce this error?
