### ISSUE TITLE
jsx specs not working when upgraded to Sprockets 3.0

### ISSUE THREAD

**Issue by mockdeep** [modeset/teaspoon#434]
We just upgraded to Sprockets 3.0 and everything in our app seems to be working alright, but tests with the extension `.js.jsx` no longer work from the command line. Booting into the browser they run fine, but from CLI we just get the cryptic "Syntax error: parse error" from phantomjs and:

```
Finished in 0.00200 seconds
0 examples, 0 failures
```

Not sure if this is a teaspoon issue, but figured I'd start here. We're using `react-rails` which adds `.js.jsx` extensions to the asset pipeline.

**Comment by mockdeep** [comment]
We have our matcher configured as:

```ruby
suite.matcher = 'spec/javascripts/**/*_spec.{js,js.jsx}'
```

**Comment by mikepack** [comment]
@mockdeep thanks for reporting this bug. I'll try to spend some turkey time looking into it. Do you know if it's specific to `.jxs` extensions?

**Comment by mockdeep** [comment]
@mikepack Sorry, we only use `.js` and `.jsx` in our javascripts folder, so not sure if other extensions are a problem. We are using `haml` in our fixtures, and those seem to be fine.

**Comment by mikepack** [comment]
The reason this is happening is because Teaspoon calls `#logical_path` on a sprockets asset in order to get a file URL that can be requested from the browser. We assume this returns a `.js` extension every time, but this is not the case with `.js.jsx` extensions, in which case it returns a `.jsx` extension.

This seems like it could be one of two things:

- Teaspoon should not use `#logical_path` but I'm not currently aware of another way to determine the URL for a sprockets asset.
- It's upstream in the `react-rails` asset pipeline integration and they need specify a `.js` extension for `#logical_path`.

**Comment by mockdeep** [comment]
@mikepack how are other extensions like `.coffee` handled?

**Comment by mikepack** [comment]
It's mostly handled by sprockets. Sorry, I didn't provide a good resolution for the interim. If you're on Teaspoon 1.1.x, try setting this configuration:

```ruby
config.suite do |suite|
  suite.js_extensions = [/(\.js)?.coffee/, /(\.js)?.es6/, ".es6.js", ".js.jsx"]
end
```

**Comment by mockdeep** [comment]
Thanks! At first blush it looks like that fixed it for me.

**Comment by mikepack** [comment]
:+1:
