### ISSUE TITLE
Errors outside of tests don't cause the test run to fail

### ISSUE THREAD

**Issue by bouk** [modeset/teaspoon#479]
This seems to have been discussed before in previous issues, but we've ran into multiple problems at Shopify where something in our javascript bundle throw a SyntaxError or ReferenceError or whatever, which would then not make Teaspoon fail and instead cause our CI to silently succeed and us to miss it.

I propose that we make Teaspoon fail the test run if there's an error before `Teaspoon.execute` is ran, as that will make it non-disrupting when there's errors in asynchronous things, but still makes sure this doesn't silently let errors slip through.

**Comment by bouk** [comment]
previous issues; https://github.com/modeset/teaspoon/issues/445 https://github.com/modeset/teaspoon/issues/425

**Comment by jejacks0n** [comment]
Yeah, I've been torn on this because it doesn't indicate a real failure directly. That being said, it's an easy fix with phantomjs, but may not be true elsewhere.

If you decide to look into this I tend to think we might need to do this at the controller level (suite_controller) and handle that exception by ending everything.

---
Jeremy Jackson

**Comment by bouk** [comment]
fixed
