### ISSUE TITLE
Console.log prevents use of teaspoon on IE8

### ISSUE THREAD

**Issue by tommeier** [modeset/teaspoon#91]
Hi,

I'm spinning up teaspoon across a selenium grid, but the use of:

https://github.com/modeset/teaspoon/blob/master/app/assets/javascripts/teaspoon/base/teaspoon.coffee#L45
`console.log` leads to this error being displayed.

Is this absolutely required? Or can we stub it out for IE8 JS tests?

Cheers,

Tom

**Comment by mcasimir** [comment]
Sorry i'm stuck here too. Is there a way to report to teaspoon independently from `console`? Any weird workaround would help here. I need to test IE8 somehow.

**Comment by mcasimir** [comment]
![schermata 2015-07-14 alle 00 22 22](https://cloud.githubusercontent.com/assets/334881/8662319/acae2984-29be-11e5-8c83-5717f1b0cb7e.png)

**Comment by mikepack** [comment]
@mcasimir can you provide a stack trace pointing back to Teaspoon? Also, what version of Teaspoon are you running?

**Comment by mcasimir** [comment]
```
teaspoon --version
1.0.2
```

```
Selenium::WebDriver::Error::TimeOutError: Timed out
/Users/maurizio/.rvm/gems/ruby-1.9.3-p545@iub/gems/selenium-webdriver-2.46.2/lib/selenium/webdriver/common/wait.rb:76:in `until'
/Users/maurizio/Sites/iub/lib/teaspoon/driver/browserstack.rb:73:in `run_specs'
/Users/maurizio/.rvm/gems/ruby-1.9.3-p545@iub/gems/teaspoon-1.0.2/lib/teaspoon/console.rb:55:in `run_specs'
/Users/maurizio/.rvm/gems/ruby-1.9.3-p545@iub/gems/teaspoon-1.0.2/lib/teaspoon/console.rb:44:in `block in execute_without_handling'
/Users/maurizio/.rvm/gems/ruby-1.9.3-p545@iub/gems/teaspoon-1.0.2/lib/teaspoon/console.rb:42:in `each'
/Users/maurizio/.rvm/gems/ruby-1.9.3-p545@iub/gems/teaspoon-1.0.2/lib/teaspoon/console.rb:42:in `inject'
/Users/maurizio/.rvm/gems/ruby-1.9.3-p545@iub/gems/teaspoon-1.0.2/lib/teaspoon/console.rb:42:in `execute_without_handling'
/Users/maurizio/.rvm/gems/ruby-1.9.3-p545@iub/gems/teaspoon-1.0.2/lib/teaspoon/console.rb:27:in `execute'
/Users/maurizio/.rvm/gems/ruby-1.9.3-p545@iub/gems/teaspoon-1.0.2/lib/teaspoon/console.rb:23:in `failures?'
/Users/maurizio/.rvm/gems/ruby-1.9.3-p545@iub/gems/teaspoon-1.0.2/lib/tasks/teaspoon.rake:12:in `block in <top (required)>'
/Users/maurizio/.rvm/gems/ruby-1.9.3-p545@iub/bin/ruby_executable_hooks:15:in `eval'
/Users/maurizio/.rvm/gems/ruby-1.9.3-p545@iub/bin/ruby_executable_hooks:15:in 
```

**Comment by mikepack** [comment]
I didn't realize you were running IE8 tests from the CLI. I think what's happening here is that Teaspoon attempts to `console.log`, it fails, and Teaspoon throws an exception. IIRC, IE8 just stops executing all future JS after encountering an exception. This seems like [the offending lines](https://github.com/modeset/teaspoon/blob/master/app/assets/javascripts/teaspoon/teaspoon.coffee#L60-L62):

```coffeescript
try console.log(arguments...)
catch e
  throw new Error("Unable to use console.log for logging")
```

I would imagine the error being thrown is because it's fatal in most browsers not to have `console.log` when running on the CLI, but this is not the case with Selenium-driven browsers.

@jejacks0n do you think failing silently here would cause us other headaches? eg:

```coffeescript
console?.log?(arguments...)
```

**Comment by jejacks0n** [comment]
Yes, sort of. If it's run via CLI using selenium+ie it would simply not generate any output. That fail is there because it technically can't use anything that doesn't have console.log when run via CLI.

---
Jeremy Jackson

**Comment by mikepack** [comment]
Except for Selenium, which polls for `Teaspoon.getMessages()`, no? Doesn't seem like a need for `console.log` there.

**Comment by jejacks0n** [comment]
Good point. How do the messages make it into Teaspoon.getMessages? I honestly don't recall and can't easily check.

---
Jeremy Jackson

**Comment by mikepack** [comment]
The same logging mechanism is used for both console-based and non-console-based drivers:

```coffeescript
@log: ->
  Teaspoon.messages.push(arguments[0])
  try console.log(arguments...)
  catch e
    throw new Error("Unable to use console.log for logging")
```

If the driver is fetching the messages, like Selenium or CapybaraWebkit, it calls:

```coffeescript
@getMessages: ->
  messages = Teaspoon.messages
  Teaspoon.messages = []
  messages
```

periodically via:

```coffeescript
Teaspoon.getMessages();
```

If the driver is listening for `console.log`, it never calls `Teaspoon.getMessages()`. So message polling drivers effectively don't need `console.log` at all, so it seems safe to fail silently instead of throw an exception.

**Comment by jejacks0n** [comment]
Sweet. :+1:

**Comment by mcasimir** [comment]
@mikepack @jejacks0n So what u suggest? 

I'm gonna add a `driver.execute "console = { log: function(){} }"` before to load the page. 

Nothing else comes in my mind.

Thanks

**Comment by mikepack** [comment]
I will apply a fix and it will need to go through the release process. What you have is what @jejacks0n suggested higher up in this thread. Seems like the only intermediary fix for right now.
